#!/bin/bash

set -e # Exit if any command fails

print_usage() {
    echo "Script for committing, interactive rebasing, squashing and amending of WIP-commits"
    echo
    echo "Usage: gitwip [ -m <msg> | -r | -s | -a | -h ] "
    echo
    echo "The default behaviour is to commit the files in the staging area"
    echo "with the message \"WIP-<number>\", based on the number of previous WIP-commits."
    echo "Commit, rebase and amend will temporarily disable any annoying hooks."
    echo
    echo "     -m <msg>             Appends \": <msg>\" to the commit message"
    echo "     -r | --rebase        Starts an interactive rebase for all latest WIP-commits"
    echo "     -s | --squash        Squash all latest WIP-commits into the first non-WIP commit"
    echo "     -a | --amend         Just a normal amend, but without any hooks"
    echo
    echo "     -h | --help          This usage screen"
}

# Check if there are any wip commits
check_wip_count() {
    if [ $wip_count -lt 1 ]; then
        echo "There are no WIP-commits! Exiting..."
        exit 0
    fi
}

wip_commit() {
    # Construct commit message
    commit_msg="WIP-$wip_count$@"
    git -c core.hooksPath=/dev/null commit -m "$commit_msg"
}

wip_rebase() {
    check_wip_count
    git -c core.hooksPath=/dev/null rebase HEAD~$(($wip_count + 1)) --interactive
}

wip_squash() {
    check_wip_count
    git reset --soft HEAD~$wip_count
    git commit --amend
}

wip_amend() {
    check_wip_count
    git -c core.hooksPath=/dev/null commit --amend
}

# Get first 20 subject lines
subjects=$(git log --pretty=format:"%s" -n 20)

# Match until the first line that does not start with "WIP" (including first non-WIP line)
# Count the number of lines, and subtract 1 to get number of WIP-commits
wip_count=$(($(awk '1;/^[^WIP]/{exit}' <(echo "$subjects") | wc -l ) - 1))

if [ $# -gt 0 ]; then
    case $1 in
        -m)
            shift 1
            wip_commit ": $@"
            ;;
        --rebase | -r)
            wip_rebase
            ;;
        --squash | -s)
            wip_squash
            ;;
        --amend | -a)
            wip_amend
            ;;
        --help | -h)
            print_usage
            ;;
        *)
            print_usage
            exit 1
            ;;
    esac
else
    wip_commit
fi

exit 0
